let g:SimplenoteUsername = $EMAIL
let g:SimplenotePassword = $PASSWORD

filetype indent plugin on
syntax on

let mapleader = "\<Space>" "sets leader to space key. This must happen here due to some plugins load order

if &loadplugins
  if has('packages')
    packloadall
    silent! helptags ALL
  endif
  " else
  "   source $HOME/.vim/pack/bundle/opt/vim-pathogen/autoload/pathogen.vim
  "   call pathogen#infect('pack/bundle/start/{}')
  " endif
endif
