#!/bin/bash

BATTERY=0
BATTERY_INFO=$(acpi -b | grep "Battery ${BATTERY}")
BATTERY_STATE=$(echo "${BATTERY_INFO}" | grep -wo "Full\|Charging\|Discharging")
BATTERY_POWER=$(echo "${BATTERY_INFO}" | grep -o '[0-9]\+%' | tr -d '%')
BATTERY_POWER_REMAINING=$(acpi -b | awk '{print$5}')
URGENT_VALUE=10

# if [[ "${BATTERY_STATE}" = "Charging" ]]; then
#   echo "${BATTERY_POWER}%+ ${BATTERY_POWER_REMAINING}"
#   echo "${BATTERY_POWER}%+ ${BATTERY_POWER_REMAINING}"
#   echo ""
# elif [[ "${BATTERY_STATE}" = "Discharging" ]]; then
#   echo "${BATTERY_POWER}%- ${BATTERY_POWER_REMAINING}"
#   echo "${BATTERY_POWER}%- ${BATTERY_POWER_REMAINING}"
#   echo ""
# else
#   echo "${BATTERY_POWER}%"
#   echo "${BATTERY_POWER}%"
#   echo ""
# fi
# 
# if [[ "${BATTERY_POWER}" -le "${URGENT_VALUE}" ]]; then
#   exit 33
# fi

if [ "${BATTERY_POWER}" -le 10 ]; then
	echo "${BATTERY_POWER}% CHARGE LAPTOP"
	# notify-send "LOW POWER"
	# echo "hi"
else
	echo "${BATTERY_POWER}% ${BATTERY_POWER_REMAINING}"
fi
