#!/bin/bash
mkdir -p /etc/systemd/system/getty@tty1.service.d/ && \
	cat << EOF > /etc/systemd/system/getty@tty1.service.d/override.conf
[Service]
ExecStart=
ExecStart=-/usr/bin/agetty --autologin $USERNAME --noclear %I $TERM
EOF
