#!/usr/bin/bash
brightness=$(cat /sys/class/backlight/intel_backlight/brightness)
maxBrightness=$(cat /sys/class/backlight/intel_backlight/max_brightness)

if (($brightness < maxBrightness-50)); then
  let brightness=$brightness+50
  echo "echo $brightness > /sys/class/backlight/intel_backlight/brightness" | sudo zsh #or bash
fi
